# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alliecode < Formula
  desc "Open-source, model-agnostic AI coding agent"
  homepage "https://github.com/alliecatowo/alliecode"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alliecatowo/alliecode/releases/download/v0.1.0/alliecode_0.1.0_darwin_amd64.tar.gz"
      sha256 "7090856b8c24e54a6195238f75e2bf6e49b36ab5f395536c7f08d90db4e6ddb7"

      define_method(:install) do
        bin.install "ac"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alliecatowo/alliecode/releases/download/v0.1.0/alliecode_0.1.0_darwin_arm64.tar.gz"
      sha256 "20e110539fbfe8ab43dc0915c803349340e09c67f46c3d1ca3c061e8df82cbff"

      define_method(:install) do
        bin.install "ac"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alliecatowo/alliecode/releases/download/v0.1.0/alliecode_0.1.0_linux_amd64.tar.gz"
      sha256 "9d1148b100df1c014f1130d90c9e07a860b527d9e2d1c24d80405904386a89dc"
      define_method(:install) do
        bin.install "ac"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alliecatowo/alliecode/releases/download/v0.1.0/alliecode_0.1.0_linux_arm64.tar.gz"
      sha256 "44b27da81a1effa5a0133a2e14700bd5a508559f4eedbc76701e0c3a498b08b8"
      define_method(:install) do
        bin.install "ac"
      end
    end
  end
end
