# Homebrew formula for git-why, a Node CLI published to npm as @alliecatowo/git-why.
# Generated by the update-homebrew job in alliecatowo/git-why
# (.github/workflows/release.yml) on each stable release. Do not edit by hand.
class GitWhy < Formula
  desc "Semantic archaeology for Git. Find the history that explains the code"
  homepage "https://github.com/alliecatowo/git-why"
  url "https://registry.npmjs.org/@alliecatowo/git-why/-/git-why-0.1.2.tgz"
  sha256 "0d00d3aeeea674eef1a48944cbda8d872d2db9bf768346e60f215850e5277458"
  license "Apache-2.0"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/git-why --version")
  end
end
