# Homebrew formula for lumen. Generated by the update-homebrew job in
# alliecatowo/lumen (.github/workflows/release.yml) on each stable release. Do not edit by hand.
class Lumen < Formula
  desc "Markdown-native, statically typed language for deterministic AI-native workflows"
  homepage "https://github.com/alliecatowo/lumen"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/alliecatowo/lumen/releases/download/v0.6.2/lumen-macos-arm64.tar.gz"
      sha256 "e8a419f0b34dc67c478a0f434bfc1a75dee9747b88d18c929fb14dfca7879c89"
    end
    on_intel do
      url "https://github.com/alliecatowo/lumen/releases/download/v0.6.2/lumen-macos-x64.tar.gz"
      sha256 "dc33d3853d7a391168b567b6d66d122233c673af3c47b45828b2d6c1bc87c911"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/alliecatowo/lumen/releases/download/v0.6.2/lumen-linux-arm64.tar.gz"
      sha256 "078b2f0cacc22ae77c804ae7cf9f492a79cf218023487f5b788d3f651947000a"
    end
    on_intel do
      url "https://github.com/alliecatowo/lumen/releases/download/v0.6.2/lumen-linux-x64-musl.tar.gz"
      sha256 "509e954164d2bd8c8bf1d3592af1ef9c8b50c6ea1a497a2deec3b3d14aeba6a2"
    end
  end

  def install
    bin.install "lumen", "lumen-lsp"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lumen --version")
  end
end
