# Homebrew formula for lumen. Generated by the update-homebrew job in
# alliecatowo/lumen (.github/workflows/release.yml) on each stable release. Do not edit by hand.
class Lumen < Formula
  desc "Markdown-native, statically typed language for deterministic AI-native workflows"
  homepage "https://github.com/alliecatowo/lumen"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/alliecatowo/lumen/releases/download/v0.6.3/lumen-macos-arm64.tar.gz"
      sha256 "d0ec8ec13422acd0e5041e9b4c625c812d206232e8affeac956670912f7d0963"
    end
    on_intel do
      url "https://github.com/alliecatowo/lumen/releases/download/v0.6.3/lumen-macos-x64.tar.gz"
      sha256 "f029fbbdb3d28287a93c789498b2a25e6e6bfa791550c186fdbb4674bce8a637"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/alliecatowo/lumen/releases/download/v0.6.3/lumen-linux-arm64.tar.gz"
      sha256 "317158f43ff198d01e32ef4f54191919f7c37a25dbb573c640a90c2c6926ad46"
    end
    on_intel do
      url "https://github.com/alliecatowo/lumen/releases/download/v0.6.3/lumen-linux-x64-musl.tar.gz"
      sha256 "702ea09b652caa348d199495b99f0b2fbe2640f60f5a05fefcb113c99e57dd97"
    end
  end

  def install
    bin.install "lumen", "lumen-lsp"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lumen --version")
  end
end
