# Homebrew formula for lumen. Generated by the update-homebrew job in
# alliecatowo/lumen (.github/workflows/release.yml) on each stable release. Do not edit by hand.
class Lumen < Formula
  desc "Markdown-native, statically typed language for deterministic AI-native workflows"
  homepage "https://github.com/alliecatowo/lumen"
  version "0.5.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/alliecatowo/lumen/releases/download/v0.5.2/lumen-macos-arm64.tar.gz"
      sha256 "152152628038005b5aabe3d7b0bd16819549c66b240fc2f15c683213c0e637c3"
    end
    on_intel do
      url "https://github.com/alliecatowo/lumen/releases/download/v0.5.2/lumen-macos-x64.tar.gz"
      sha256 "8026a3c7e10249fdc63b0339142ce5a6b5529e217a67db024f368fe159d7d6f5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/alliecatowo/lumen/releases/download/v0.5.2/lumen-linux-arm64.tar.gz"
      sha256 "1b67592f5ff021c17ca64f0670dbfdc3f20034fee92d75e34da3ff3401063961"
    end
    on_intel do
      url "https://github.com/alliecatowo/lumen/releases/download/v0.5.2/lumen-linux-x64-musl.tar.gz"
      sha256 "c1c4ab9602a35ece569fe8ea4ee161e7b3cfb9208a3a9e09c03c5c39fd6021c4"
    end
  end

  def install
    bin.install "lumen", "lumen-lsp"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lumen --version")
  end
end
