# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Patchrun < Formula
  desc "Run any command as a patch before it touches your repo"
  homepage "https://github.com/alliecatowo/patchrun"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alliecatowo/patchrun/releases/download/v0.1.0/patchrun_0.1.0_darwin_amd64.tar.gz"
      sha256 "0f030c5454821e711b1663d159606afea3294f4be7cf06bad1783d4ac61fee44"

      define_method(:install) do
        bin.install "patchrun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alliecatowo/patchrun/releases/download/v0.1.0/patchrun_0.1.0_darwin_arm64.tar.gz"
      sha256 "5dedfe9499cb83fad0531f32efa2d849962802548928c7ac930674892aa30a91"

      define_method(:install) do
        bin.install "patchrun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alliecatowo/patchrun/releases/download/v0.1.0/patchrun_0.1.0_linux_amd64.tar.gz"
      sha256 "6f4fcc0480b97bbe73bb7c2313f07300c4bb82940e3d5bed6392fad43875de53"
      define_method(:install) do
        bin.install "patchrun"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alliecatowo/patchrun/releases/download/v0.1.0/patchrun_0.1.0_linux_arm64.tar.gz"
      sha256 "ac422c6c5d2a7311de0b83fddb198a1b3a79acc6ff850d9fd0bf9aa0ba61902d"
      define_method(:install) do
        bin.install "patchrun"
      end
    end
  end

  test do
    assert_match "Usage:", shell_output("#{bin}/patchrun --help 2>&1")
  end
end
