# Homebrew formula for puml. Generated by the update-homebrew job in
# alliecatowo/puml (.github/workflows/release.yml) on each stable release. Do not edit by hand.
class Puml < Formula
  desc "Fast, no-Java PlantUML-compatible diagram renderer"
  homepage "https://github.com/alliecatowo/puml"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/alliecatowo/puml/releases/download/v0.2.5/puml-aarch64-apple-darwin.tar.gz"
      sha256 "36e4e0a2eaec6e9f37ac6caf57537a23d176693e28e320c83bed37fc69af3977"
    end
    on_intel do
      url "https://github.com/alliecatowo/puml/releases/download/v0.2.5/puml-x86_64-apple-darwin.tar.gz"
      sha256 "6bef496dfc855e17cfb2ac5d734f34a7274cc29ecda4676451254cb9897f56d5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/alliecatowo/puml/releases/download/v0.2.5/puml-aarch64-unknown-linux-musl.tar.gz"
      sha256 "8b0afcc81c94d033a6d78646aa4559dbfd7693ca9e234d2ae6d1a84706a05515"
    end
    on_intel do
      url "https://github.com/alliecatowo/puml/releases/download/v0.2.5/puml-x86_64-unknown-linux-musl.tar.gz"
      sha256 "dc2a946620b8572a20827f17efdbf3e0f9b720560d2d3027c76f47f4eac63e85"
    end
  end

  def install
    bin.install "puml"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/puml --version")
  end
end
