# Homebrew formula for puml. Generated by the update-homebrew job in
# alliecatowo/puml (.github/workflows/release.yml) on each stable release. Do not edit by hand.
class Puml < Formula
  desc "Fast, no-Java PlantUML-compatible diagram renderer"
  homepage "https://github.com/alliecatowo/puml"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/alliecatowo/puml/releases/download/v0.2.6/puml-aarch64-apple-darwin.tar.gz"
      sha256 "bc390e6e2ae97f9bcd9a4b284f6a2d11838eeae692af655e84822caa38aa5d8f"
    end
    on_intel do
      url "https://github.com/alliecatowo/puml/releases/download/v0.2.6/puml-x86_64-apple-darwin.tar.gz"
      sha256 "b5bb9d8b39275f6a38810b39ab83671af500cfdb1b9bbc782485997cf39ba4a5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/alliecatowo/puml/releases/download/v0.2.6/puml-aarch64-unknown-linux-musl.tar.gz"
      sha256 "72f6554ae71c16c45b0880d55e0ee794d37047570a6c7b124a822032d9218323"
    end
    on_intel do
      url "https://github.com/alliecatowo/puml/releases/download/v0.2.6/puml-x86_64-unknown-linux-musl.tar.gz"
      sha256 "dbc3af658731daacafb751c05d67fcf76419b5ef143bcafbaaba9548c40a6162"
    end
  end

  def install
    bin.install "puml"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/puml --version")
  end
end
