# Homebrew formula for puml. Generated by the update-homebrew job in
# alliecatowo/puml (.github/workflows/release.yml) on each stable release. Do not edit by hand.
class Puml < Formula
  desc "Fast, no-Java PlantUML-compatible diagram renderer"
  homepage "https://github.com/alliecatowo/puml"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/alliecatowo/puml/releases/download/v0.2.2/puml-aarch64-apple-darwin.tar.gz"
      sha256 "434951d87601722766f6f9c1feab714c0b7f6923ed7183afd63305aaee138c2b"
    end
    on_intel do
      url "https://github.com/alliecatowo/puml/releases/download/v0.2.2/puml-x86_64-apple-darwin.tar.gz"
      sha256 "67e27e54269fe2ea794aa3667f08bc3b571f2c8b2da85c84719b8df7aad73dcc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/alliecatowo/puml/releases/download/v0.2.2/puml-aarch64-unknown-linux-musl.tar.gz"
      sha256 "4a5910177b4a6898100da1f7dbb30ef74c00efb9040760a02ccd677b145473df"
    end
    on_intel do
      url "https://github.com/alliecatowo/puml/releases/download/v0.2.2/puml-x86_64-unknown-linux-musl.tar.gz"
      sha256 "086decb4605c9ff19195a8fb792824a5c2e7cb904bc1e1adf09a232327954906"
    end
  end

  def install
    bin.install "puml"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/puml --version")
  end
end
