# Homebrew formula for ticket-master (the tm CLI). Generated by the update-homebrew
# job in alliecatowo/ticket-master (.github/workflows/release.yml) on each stable
# release. Do not edit by hand.
class TicketMaster < Formula
  desc "Interactive coding agent with a ticket-powered background crew (the tm CLI)"
  homepage "https://github.com/alliecatowo/ticket-master"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/alliecatowo/ticket-master/releases/download/v0.1.2/tm-aarch64-apple-darwin.tar.gz"
      sha256 "632c0cc441c7fe8430ef5b8324050993c244ad3eaa45e96bce8f0bccde082b9b"
    end
    on_intel do
      url "https://github.com/alliecatowo/ticket-master/releases/download/v0.1.2/tm-x86_64-apple-darwin.tar.gz"
      sha256 "6a6737dd2351e7d0975a6babb91720dc20d129f23c2368b9dc9a00ce95b5de52"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/alliecatowo/ticket-master/releases/download/v0.1.2/tm-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "b00d8a56ec950183facff09ac1390b5e3a25c7fc36894da21b45d7ca0767955b"
    end
    on_intel do
      url "https://github.com/alliecatowo/ticket-master/releases/download/v0.1.2/tm-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "7af6bc57b35dc9fd66f9eee94322232b46f190773a3c76af624a2c983f5322f8"
    end
  end

  def install
    # The tarball holds one tm-<triple>/ directory: bin/tm plus share/tm/web
    # (the web client tm serve finds next to the binary).
    bin.install "bin/tm"
    (share/"tm").install "share/tm/web"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tm --version")
  end
end
