# Homebrew formula for ticket-master (the tm CLI). Generated by the update-homebrew
# job in alliecatowo/ticket-master (.github/workflows/release.yml) on each stable
# release. Do not edit by hand.
class TicketMaster < Formula
  desc "Interactive coding agent with a ticket-powered background crew (the tm CLI)"
  homepage "https://github.com/alliecatowo/ticket-master"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/alliecatowo/ticket-master/releases/download/v0.1.3/tm-aarch64-apple-darwin.tar.gz"
      sha256 "51a31f76be2900dd79a7f9d259eb3d33e62f6a29933b2d9112421937fad927c3"
    end
    on_intel do
      url "https://github.com/alliecatowo/ticket-master/releases/download/v0.1.3/tm-x86_64-apple-darwin.tar.gz"
      sha256 "c61899ba5c3dfc202209c47e29841f0e00b964996949f4f43ca4ea49471828b2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/alliecatowo/ticket-master/releases/download/v0.1.3/tm-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "a3a46c610222f7d0833e24ba6809db7b11f6fc0a2964029f2abef92433962244"
    end
    on_intel do
      url "https://github.com/alliecatowo/ticket-master/releases/download/v0.1.3/tm-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "4d6df3d26f7a0ff478b7e278dccbbee2e0ae4af4618141fef7c05d3e8151b877"
    end
  end

  def install
    # The tarball holds one tm-<triple>/ directory: bin/tm plus share/tm/web
    # (the web client tm serve finds next to the binary).
    bin.install "bin/tm"
    (share/"tm").install "share/tm/web"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tm --version")
  end
end
