# Homebrew formula for ticket-master (the tm CLI). Generated by the update-homebrew
# job in alliecatowo/ticket-master (.github/workflows/release.yml) on each stable
# release. Do not edit by hand.
class TicketMaster < Formula
  desc "Interactive coding agent with a ticket-powered background crew (the tm CLI)"
  homepage "https://github.com/alliecatowo/ticket-master"
  version "0.1.1"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/alliecatowo/ticket-master/releases/download/v0.1.1/tm-aarch64-apple-darwin.tar.gz"
      sha256 "56db635898434a9e2d0da5ab29e13d54b3b02a225a39a4e46080e85d2a5d6151"
    end
    on_intel do
      url "https://github.com/alliecatowo/ticket-master/releases/download/v0.1.1/tm-x86_64-apple-darwin.tar.gz"
      sha256 "954024ffd3a5828a546c9ffecb89114f7539a31e71e19dda9687c85d370fcf3e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/alliecatowo/ticket-master/releases/download/v0.1.1/tm-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "078d694d20422bb186a685ee92211bb65faab22e0ca4a059269f1796b3423d1d"
    end
    on_intel do
      url "https://github.com/alliecatowo/ticket-master/releases/download/v0.1.1/tm-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "8de8d3a3d101f2f18fe0fa5e28775631f4c9d99d207135294405178d37391b4a"
    end
  end

  def install
    # The tarball holds one tm-<triple>/ directory: bin/tm plus share/tm/web
    # (the web client tm serve finds next to the binary).
    bin.install "bin/tm"
    (share/"tm").install "share/tm/web"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tm --version")
  end
end
